export const TOUCH_LAST_SAVED = 'TOUCH_LAST_SAVED'
export const SET_CURRENT_NOTE = 'SET_CURRENT_NOTE'
export const SET_CURRENT_NOTE_ID = 'SET_CURRENT_NOTE_ID'
export const PREPEND_TO_NOTES = 'PREPEND_TO_NOTES'
export const DELETE_NOTE = 'DELETE_NOTE'

export const SET_SAVE_TIMEOUT = 'SET_SAVE_TIMEOUT'
export const CLEAR_SAVE_TIMEOUT = 'CLEAR_SAVE_TIMEOUT'
